name: Release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'gh-token'

jobs:
  Update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: "Checkout repo"
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Calculate new SHA256 hash"
      run: |
        new_sha="$(shasum -a 256 gh-token | sed -r 's/gh-token/ghtoken/g')"
        sed -r "s/echo \"[0-9a-f]{64}  ghtoken\"/echo \"$new_sha\"/g" -i README.md
    - name: "Commit and push updates"
      uses: EndBug/add-and-commit@998652d28d7702d095d40f52ae42982a80ae8c7d
      with:
        author_name: Link-
        author_email: bassem@interop.link
        message: 'Updating sha256 hash value'
        add: 'README.md'
